# Build stage
FROM node:lts-bullseye-slim AS build
WORKDIR /usr/src/client
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Run stage
FROM nginx
ENV NODE_ENV production
COPY --from=build /usr/src/client/dist /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 3030
CMD ["nginx", "-g", "daemon off;"]


